### ISSUE TITLE
Question about PCB and how to connect to esp32

### ISSUE THREAD

**Issue by rotda** [mkrasselt1/esp32-mdb-master#1]
Hi ,

can you share more information how you have connected the esp32 to the MDB Bus ? And explain a little bit more about the PCB Layout . We would like to connect to coffee machine via MDB and ESP32 with RFID Read

**Comment by mkrasselt1** [comment]
Sadly this is the wrong side of the mdb bus. this code implements a mdb host device - it emulates the coffee machine - not the slave device like a cashless device.  (i have done that as weel, but cant pusblish the code easely)

but for the rfid device itself - you only need two fast optocoupplers and attach them between mdb rx tx / and µc rx nad tx
You could referr to this project from nottingham university 
https://github.com/NottingHack/nv-vend-PCB
https://wiki.nottinghack.org.uk/wiki/Vending_Machine
