### ISSUE TITLE
Slave implementation overview

### ISSUE THREAD

**Issue by note5** [mkrasselt1/esp32-mdb-master#2]
Thank you for thos awesome job. I see on other issue that you have also implemented slave. I would like to simulate a cashless device as slave using esp32. Please provide some pointers when it comes to making the connections to a VMC and how you tackle the serial communication. (Not asking for the code you do not want to  share :))

**Comment by mkrasselt1** [comment]
Hello :)
Of course you do :D but - it's nothing different from the mdb interface specification to be found on the internet.
you need some fast optocopplers between tx and ground and rx and ground. i am using the rmt driver to send and recieve the mdb frames. code to recieving and sending is also simmilar to the master.

**Comment by mkrasselt1** [comment]
but we almost completly redesigned the master as wee, there will be an update soon

**Comment by note5** [comment]
Ah, what type optocouplers would you recommend I use? I also see some circuits that use hex inverter , Is this neccessary ?

**Comment by mkrasselt1** [comment]
no, hex inverter (you mean binary/signal inverter right?) is not necesary, as you could fix that in software

**Comment by mkrasselt1** [comment]
And LTV-827 works a a optocoupler, just make shure yours is fast enought for 9600 baud ;)

**Comment by tomeroto** [comment]
hi, do you have MDV SLAVE as Bill Validator example source for ESP32?

**Comment by mkrasselt1** [comment]
You mean a code That mimics the bill validator?

**Comment by tomeroto** [comment]
> You mean a code That mimics the bill validator?

yes that's right, MDB SLAVE with implementation as Bill Validator.

**Comment by mkrasselt1** [comment]
no this is master code only
