### ISSUE TITLE
VIDEO TUTORIAL

### ISSUE THREAD

**Issue by tomeroto** [mkrasselt1/esp32-mdb-master#3]
hi friend,

can you provide picture or video tutorials, im very beginner. THanks.

**Comment by mkrasselt1** [comment]
Hello :)
On what part exactly? The build environment, the board or the software(integration?) what do you have already and what do you want to do with it?

**Comment by tomeroto** [comment]
thank you for your response.
I use Arduino Uno. But I'm having trouble finding a module for integration with the MDB protocol. I want to create a master and slave, but for now I need a master first. I have difficulty reading schematics. If you have a photo of the PCB board that has been formed it might be very helpful. And photos of how to connect it to Arduino Uno.

Is your source code suitable for Arduino Uno?

**Comment by mkrasselt1** [comment]
Sadly no, as the name states - this is for esp32 only as it used a signal generator function only present in esp32 processor.
And you can't easly port it either.
You should check out:
https://github.com/LanguidSmartass/mdb-arduino-cashless
That is more suited and has nessecary documentation

**Comment by mkrasselt1** [comment]
Ad there are no available modules AFAIK - but it only needs 4 conpontents attached to two (serial) gpio pins

**Comment by tomeroto** [comment]
Ok I will try using ESP32. I try connected all lines like this picture below.

![MDB-Master-Interface](https://github.com/mkrasselt1/esp32-mdb-master/assets/4737601/a7edc669-48f9-4d73-91df-dd9035535539)

that is correct?

**Comment by mkrasselt1** [comment]
Almost yeah :)
Except that pins are
Mdb_tx.gpio_num = GPIO_NUM_32;
Mdb_rx.gpio_num = GPIO_NUM_35;

**Comment by tomeroto** [comment]
Ok I try like this picture:

![MDB-Master-Interface PNG](https://github.com/mkrasselt1/esp32-mdb-master/assets/4737601/0295d42f-8812-4e64-856e-124e2b3e1dec)

But still not working. :(
May be you have simple source code for ESP32 using Arduino IDE with function how much money inserted to BV. Thanks.

**Comment by mkrasselt1** [comment]
You are still using the wrong gpio - read my previous post again

**Comment by tomeroto** [comment]
Ups sorry, okay I was follow like this picture:

![MDB-Master-Interface PNG](https://github.com/mkrasselt1/esp32-mdb-master/assets/4737601/633ddb8f-5fe6-441e-9b41-0329b0bc6d1f)

But not working :( found this messages:

> Changer paused, caused by too many errors
> 
> Cashless Device #1 paused, caused by too many errors

**Comment by mkrasselt1** [comment]
Great, that provides at least a little feedback.
Did you try switching rx and TX pins in the esp32?
And you are you provide some pictures of the setup and components used?

**Comment by tomeroto** [comment]
do you have alternative component for SI2301 and SI2302 non SMD?

**Comment by mkrasselt1** [comment]
Just use any fast enough mosfet with Fast Switching Speed: Rise Time (tr) of 36ns and low resistance

**Comment by tomeroto** [comment]
I was try and with all components according to the circuits that you give. But its not working, may be I have wrong in joining components or different components version. Thats why is good if you have picture or video to show me how its look.

**Comment by mkrasselt1** [comment]
It's all under  /pcb
Master and slave as well and it is working.
What devices if which brands do you use and what does your circuit look like?
